### ISSUE TITLE
Cloned frontend only show homepage

### ISSUE THREAD

**Issue by mahdi-ln** [Wonderland-Money/wonderland-frontend#17]
**Note:** I'm not developer. I want to use github frontend for more safety

*Describe the bug**
Cloned frontend only show homepage and pressing "enter app" goto https://app.wonderland.money/

**Screenshots**
![image](https://user-images.githubusercontent.com/27496531/142138810-50bd1029-0c2b-44f0-b816-638a61e977cc.png)

**Desktop (please complete the following information):**
- OS: Manjaro
 - Browser chromium

**Comment by orion-git** [comment]
http://app.localhost:3000/#/stake
