### ISSUE TITLE
Wonderland Local Build Can't Navigate to Dashboard or Stake Pages

### ISSUE THREAD

**Issue by cryptoodles** [Wonderland-Money/wonderland-frontend#20]
**Describe the bug**
When building the latest repository locally, you are not auto-navigated to the staking page. Furthermore, you are unable to navigate to the Dashboard or Staking page through their direct links. The links used were:

- http://localhost:3000/#/dashboard
- http://localhost:3000/dashboard
- http://localhost:3000/#/stake
- http://localhost:3000/stake

All links above keeps the user on the main page.

**To Reproduce**
1. Clone and build repository
2. Start the development server
3. Try to navigate to the dashboard or staking pages through the URLs mentioned above
4. You stay on the same page instead of being navigated

**Expected behavior**
You should be able to navigate to the Dashboard and Staking pages when building and running the repository locally.

**Workarounds (if any)**
Could not find a work around.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: FireFox
 - Version 84.0.2 (64-bit)

**Comment by cryptoodles** [comment]
@szferguson @Turden any short term guidance you can give trying to build the repository locally? Been trying to find workarounds the past day by switching to a test network in AVAX but dont think those contracts are deployed there. We're currently only able to navigate around the home page, and not the others

**Comment by leonpw** [comment]
You can navigate to the app by going to: http://app.localhost:3000/#/dashboard
