### ISSUE TITLE
Staking TIME - 'Your Staked Balance' shows '0 MEMO'

### ISSUE THREAD

**Issue by vongoh** [Wonderland-Money/wonderland-frontend#25]
**Describe the bug**

I followed the docs to stake TIME via Metamask.  

- Transaction was 'Approved'
- Browser showed popup 'Your transaction was successfully' ( strange popup! successfully ...what?)
- 'Your Balance' shows the amount of TIME 
- 'Your Staked Balance' still shows 0

**Expected behavior**

Thought my TIME would be staked.

**Desktop (please complete the following information):**
Win10.
Chrome  96.0.4664.45

Would love to stake, thanks 👍

**Comment by Turden** [comment]
The first time you use it, you need to make two transactions. The first is 'Approved' and the second is "Stake TIME"
