### ISSUE TITLE
I want to remove the following issue

### ISSUE THREAD

**Issue by jackalstar** [Wonderland-Money/wonderland-frontend#31]
Delete `␍`eslint(prettier/prettier)

**Comment by gabbo-dam** [comment]
It is a compatibility problem with windows, if you work with macOS or Linux there should be no problem. In the case that you have windows I recommend you download [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)

**Comment by Turden** [comment]
npm run lint-fix
