### ISSUE TITLE
Balance of staked Time has disappeared!

### ISSUE THREAD

**Issue by andyg1965** [Wonderland-Money/wonderland-frontend#38]
Hi all,  I've staked some Time on Wonderland, and then wrapped it, however, by balance has now reduced to zero and shows no staked or wrapped Time or Memo.

I waited a couple of hours for the balance to update, but it hasn't....  I'm a newbie to staking on DAO's, but can't see how I did anything wrong.  Any ideas?

Appreciate your help....

**Comment by donaldma** [comment]
once you wrap your MEMO it won't display on the stake dashboard anymore. you will have to use a site like zapper.fi to track your wMEMO.

**Comment by andyg1965** [comment]
Ah ok... really apprrciate this feedback... thanks!!



Sent from my Galaxy



-------- Original message --------
From: Donald Ma ***@***.***>
Date: 28/11/2021 21:08 (GMT+00:00)
To: Wonderland-Money/wonderland-frontend ***@***.***>
Cc: andyg1965 ***@***.***>, Author ***@***.***>
Subject: Re: [Wonderland-Money/wonderland-frontend] Balance of staked Time has disappeared! (Issue #38)


once you wrap your MEMO it won't display on the stake dashboard anymore. you will have to use a site like zapper.fi to track your wMEMO.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWonderland-Money%2Fwonderland-frontend%2Fissues%2F38%23issuecomment-981152430&data=04%7C01%7C%7C0758c316f9484336c9c208d9b2b340d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737305273932020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VfqOMJMolUkNWXL3hXxi76Q3z42pnU%2B8%2FJVifYKAt04%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWWGORAAUW3UVMNR3JGDSNDUOKK5RANCNFSM5I5RRBSQ&data=04%7C01%7C%7C0758c316f9484336c9c208d9b2b340d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737305273941974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZaUBwkJdMVto4FZ6EMTFyWOaUaqNejp9bQf8exZ3%2ByM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0758c316f9484336c9c208d9b2b340d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737305273941974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j5UchiauOJv0qRgC7cHFQ9ifLNCKhpi0LJnGCyFIW30%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0758c316f9484336c9c208d9b2b340d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737305273941974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IpogkhNazsUKfqRvpZoGeDnQ4f7%2FSLuNpUkmLtIwNa8%3D&reserved=0>.
