### ISSUE TITLE
Staking Testnet

### ISSUE THREAD

**Issue by hjertefolger** [Wonderland-Money/wonderland-frontend#39]
Hello all! I would like to test this wonderful project and contracts on Testnet. I've deployed test contracts to FUJI, changed addresses and blockchain ID in front-end, minted some test token (assigning vault address to me) to test staking, but it doesn't work. Could someone please help me how to setup test environment for this project?

1. Connecting wallet to FUJI, sending test AVAX from faucet, everything works
2. Approving token went smoothly, even seen details in the approval, both contract address and token are right
3. But staking certain amount results in "ëxecution reverted" although I've got enough tokens in balance:
{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"}}
4. Contracts are not altered, everything is copy from github (except the name and symbol of test token)

Thank you very much for any help.

**Comment by donaldma** [comment]
do you have enough test AVAX for gas fees? just a hunch.

**Comment by hjertefolger** [comment]
Thank you very mich for reply 🙏 did you get it up and running in test mode?

Yeah I've got 10 test AVAX. Maybe is there something important I have to set up in Staking contract Write function? I can see functions like setContract with values _contract and _address, but I couldn't find any comments or documentation for actually setting up the contracts.
